### ISSUE TITLE
Pretrained model - wrong link? 

### ISSUE THREAD

**Issue by pelican6** [acids-ircam/AFTER#1]
Thanks for sharing the project! 
The links to both MIDI-to-Audio and Audio-to-Audio models are the same. Is this a mistake? 

Also, the downloaded model's name is "slakh_midi," and the name on the Max patch is "slakh_stream_midi." Are they the same?

Thanks!

**Comment by NilsDem** [comment]
Thanks for your interest in the project ! 
Indeed, we made a mistake on the download links. We changed them and corrected the model names in max patches and screenshots accordingly.

**Comment by pelican6** [comment]
Thanks a lot!!
